// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace FactorAnalysisML.Model.Models
{
    public class CurrencyExchangeModelInput
    {
        [ColumnName("Id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("Date"), LoadColumn(1)]
        public string Date { get; set; }


        [ColumnName("ExchangeRateUSD"), LoadColumn(2)]
        public float ExchangeRateUSD { get; set; }


        [ColumnName("ExchangeRateEUR"), LoadColumn(3)]
        public float ExchangeRateEUR { get; set; }


        [ColumnName("CreditRate"), LoadColumn(4)]
        public float CreditRate { get; set; }


        [ColumnName("GDPIndicator"), LoadColumn(5)]
        public float GDPIndicator { get; set; }


        [ColumnName("ImportIndicator"), LoadColumn(6)]
        public float ImportIndicator { get; set; }


        [ColumnName("ExportIndicator"), LoadColumn(7)]
        public float ExportIndicator { get; set; }


        [ColumnName("InflationIndex"), LoadColumn(8)]
        public float InflationIndex { get; set; }


    }
}
