// This file was auto-generated by ML.NET Model Builder. 


namespace FactorAnalysisML.Model.Models
{
    public class CurrencyExchangeModelOutput
    {
        public float Score { get; set; }
    }
}
