// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200212221801_ChangeDoubleToFloat")]
    partial class ChangeDoubleToFloat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Model.ExchangeRateFactors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("CreditRate")
                        .HasColumnType("real");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExchangeRateEUR")
                        .HasColumnType("Money");

                    b.Property<decimal>("ExchangeRateUSD")
                        .HasColumnType("Money");

                    b.Property<float>("ExportIndicator")
                        .HasColumnType("real");

                    b.Property<long>("GDPIndicator")
                        .HasColumnType("bigint");

                    b.Property<float>("ImportIndicator")
                        .HasColumnType("real");

                    b.Property<float>("InflationIndex")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("ExchangeRateFactors");
                });
#pragma warning restore 612, 618
        }
    }
}
