// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using FactorAnalysisML.Model;

namespace FactorAnalysisML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"C:\Users\gorsh\AppData\Local\Temp\4a0598cb-ca18-4dc7-bd95-0a58e315cb70.tsv";

        static void Main(string[] args)
        {
            //// Create single instance of sample data from first line of dataset for model input
            //ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            //// Make a single prediction on the sample data and print results
            //ModelOutput predictionResult = ConsumeModel.Predict(sampleData);

            //Console.WriteLine("Using model to make single prediction -- Comparing actual ExchangeRateUSD with predicted ExchangeRateUSD from sample data...\n\n");
            //Console.WriteLine($"Id: {sampleData.Id}");
            //Console.WriteLine($"Date: {sampleData.Date}");
            //Console.WriteLine($"ExchangeRateEUR: {sampleData.ExchangeRateEUR}");
            //Console.WriteLine($"CreditRate: {sampleData.CreditRate}");
            //Console.WriteLine($"GDPIndicator: {sampleData.GDPIndicator}");
            //Console.WriteLine($"ImportIndicator: {sampleData.ImportIndicator}");
            //Console.WriteLine($"ExportIndicator: {sampleData.ExportIndicator}");
            //Console.WriteLine($"InflationIndex: {sampleData.InflationIndex}");
            //Console.WriteLine($"\n\nActual ExchangeRateUSD: {sampleData.ExchangeRateUSD} \nPredicted ExchangeRateUSD: {predictionResult.Score}\n\n");
            //Console.WriteLine("=============== End of process, hit any key to finish ===============");


            ModelInput sampleData = new ModelInput
            {
                CreditRate = 30,
                GDPIndicator = 566997,
                ImportIndicator = 3081,
                ExportIndicator = 3215,
                InflationIndex = 99
            };
            ModelOutput predictionResult = ConsumeModel.Predict(sampleData);
            Console.WriteLine($"Result = {predictionResult.Score}");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: '\t',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
