// This file was auto-generated by ML.NET Model Builder. 

using System;
using FactorAnalysisML.Model.Models;
using Microsoft.ML;

namespace FactorAnalysisML.Model
{
    public class USDCurrencyExchangeConsumeModel
    {
        // For more info on consuming ML.NET models, visit https://aka.ms/model-builder-consume
        // Method for consuming model in your app
        public static CurrencyExchangeModelOutput Predict(CurrencyExchangeModelInput input)
        {

            // Create new MLContext
            var mlContext = new MLContext();

            // Load model & create prediction engine
            var modelPath = AppDomain.CurrentDomain.BaseDirectory + "USDCurrencyExchangeMLModel.zip";
            var mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<CurrencyExchangeModelInput, CurrencyExchangeModelOutput>(mlModel);

            // Use model to make prediction on input data
            var result = predEngine.Predict(input);
            return result;
        }
    }
}
